name: Create .env file

on:
  push:
    branches: [ main ]

jobs:
  create-env-file:
    runs-on: ubuntu-latest

    steps:
      - name: Create .env file
        run: |
          echo "REACT_APP_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" > .env
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
